[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}:5432/${postgres_db}"
weight = 0
pool_size = 10


[chains]
ingestor = "index_node_2"

[chains.mainnet]
shard = "primary"
provider = [ { label = "rinkeby", url = "${RINKEBY_RPC}", features = ["archive", "traces"] } ]

[deployment]
[[deployment.rule]]
indexers = [ "index_node_2" ]
match = { network = "rinkeby" }

[[deployment.rule]]
# There's no 'match', so any subgraph matches
indexers = [ "index_node_0", "index_node_1" ]


[general]
query = "query_node_0"
